
import type { FormDataState, CustomerInfo, ItemData } from './types';

export const initialCustomerInfo: CustomerInfo = {
  name: '',
  email: '',
  phone: '',
  property: '',
};

export const FLEECE_ONLY_PROPERTIES = [
  '333 Fremont',
  '909 West',
  'Addison Place',
  'Arbor Oaks',
  'Arbors at California Oaks',
  'C on Pico',
  'Cascades',
  'Chase Knolls',
  'Citra at Windermere',
  'Delaneaux',
  'Diamond Hillside',
  'Dominion Heights',
  'Duo',
  'Edgewater Crossings',
  'Fountains at Chatham Parkway',
  'Grandeville at Riverplace',
  'Heights at Hammond',
  'Indigo Park',
  'Lumina',
  'Montage',
  'Motion at Dadeland',
  'Parkside Glen',
  'Rancho Solana',
  'Saratoga Place',
  'Serenade at River Park',
  'Terra Mar',
  'Terraces at Glassford Hill',
  'The DeSota',
  'The Grove',
  'The Harrison',
  'White Sands',
  'Woodbury Park at City Centre'
];

export const PROPERTIES = [
  '150 Summit',
  '333 Fremont',
  '77 Park Avenue',
  '909 West',
  'Addison Place',
  'Apex at 290',
  'Apex Hudson Riverfront',
  'Apex Manayunk',
  'Arbor Oaks',
  'Arbors at California Oaks',
  'Arwen Vista',
  'Belmont Station',
  'Boulders at Puget Sound',
  'Brook on Janes',
  'C on Pico',
  'Cabot Crossing',
  'Cadence at Crown',
  'Carrington Park at Gulf Pointe',
  "Carroll's Creek",
  'Cascades',
  'Cedar Place',
  'Centennial',
  'Charles Bellingham',
  'Chase Arbor',
  'Chase Knolls',
  'Citra at Windermere',
  'Citra Luxury Apartments',
  'Concierge',
  'Deerfield at Indian Creek',
  'Delaneaux',
  'Diamond Hillside',
  'Dominion Heights',
  'Duo',
  'Edge 1909',
  'Edgewater Crossings',
  'Enclave at Pamalee Square',
  'Essex',
  'Fieldpointe of St. Louis',
  'Fountains at Chatham Parkway',
  'Grandeville at Riverplace',
  'Halstead',
  'Heights at Hammond',
  'Heritage at Freemason Harbour',
  'Heritage at Lakeside',
  'Hideaway at Greenbrier',
  'Independence Green',
  'Indigo Park',
  "Inigo's Crossing",
  'Jefferson at Westtown',
  'Liberty Commons',
  'Lumina',
  'Manchester Lakes',
  'Montage',
  'Motion at Dadeland',
  'One Webster',
  'Park Place of Northville',
  'Parkside Glen',
  'Rancho Solana',
  'Redbank Village',
  'Residences at Arlington Heights',
  'Residences at Falcon North',
  'Residences at Lakeside',
  'Residences at Park Place',
  'Residences at Tewksbury Commons',
  'Residences on Bedford',
  'Retreat at River Bend',
  'Royal Crest Estates',
  'Santa Fe Ridge',
  'Saratoga Place',
  'Serenade at River Park',
  'Shadow Ridge at Southlands',
  'Silverdale Ridge',
  'Spyglass at Cedar Cove',
  'Summerbrooke',
  'Summit at Red Rocks',
  'Terra Mar',
  'Terraces at Glassford Hill',
  'The Beacon',
  'The DeSota',
  'The Grove',
  'The Harrison',
  'The Parc at East 51st',
  'Trillium Heights',
  'Vue',
  'West 18th',
  'Westcliff',
  'WestEnd 25',
  'White Sands',
  'Woodbury Park at City Centre'
];

export const initialItemData = (): ItemData => ({
  id: Date.now(),
  mainChoice: '',
  
  onboardingShirtSize: '',
  onboardingBadgePic: [],
  onboardingStaffName: '',
  onboardingStaffTitle: '',
  onboardingBadgeGuidelinesVerified: false,
  
  generalCategory: '',
  poloQuantities: {},
  hoodieQuantities: {},
  winterJacketQuantities: {},
  hatQuantity: '',
  winterBeanieQuantity: '',
  winterBeanieStyle: '',
  replacementBadgePic: [],
  replacementStaffName: '',
  replacementStaffTitle: '',
  replacementBadgeGuidelinesVerified: false,
  
  signageType: '',
  doormatSize: '',
  yardSignSize: '',
  bannerSize: '',
  signageQuantity: ''
});

export const initialFormData: FormDataState = {
  customerInfo: initialCustomerInfo,
  items: [initialItemData()]
};

export const POLO_SIZES = ['Extra Small', 'Small', 'Medium', 'Large', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'];
export const WINTER_JACKET_SIZES = ['Extra Small', 'Small', 'Medium', 'Large', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'];

